### ISSUE TITLE
Missing this documentation file.

### ISSUE THREAD

**Issue by onyxring** [tustin2121/ORLibrary-archive#1]
I don't see the ORLibrary Developer's Guide in this.  Feels like it should be kept here.  I've attached it.  

Let me know if you have any questions.

Thanks!

Jim
[orldg.pdf](https://github.com/tustin2121/ORLibrary-archive/files/15046518/orldg.pdf)

**Comment by tustin2121** [comment]
Added. Thanks so much for the work you've done!
